services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8889:8888"
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017/

  db:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: